auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  wal:
    enabled: true
    dir: /loki/wal

  chunk_target_size: 1048576
  max_chunk_age: 1h
  max_chunk_idle: 5m

  chunk_store_config:
    max_look_back_period: 0s

  max_transfer_retries: 0
  chunk_idle_period: 2m

  time_to_retire: 30m

  lifecycles:
    - stage: active
      retention: 1d
    - stage: expired
      retention: 1w

  chunk_target_size: 1048576

# Disabling index retention
index:
  enabled: false

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

# Promtail settings
scrape_configs:
  - job_name: 'mongo-logs'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'mongo-logs'
          __path__: /var/log/mongodb/*.log

# Adding volume configuration
limits_config:
  volume_enabled: true

